$(document).ready(function(){
    $("#design-toggle").click(function(){
        $("#design-icon").toggle();
        $("#design-explanation").toggle();
    });
    $("#development-toggle").click(function(){
        $("#development-icon").toggle();
        $("#development-explanation").toggle();
    });
    $("#product-toggle").click(function(){
        $("#product-icon").toggle();
        $("#product-explanation").toggle();
    });
});